### ISSUE TITLE
API Retries on bootstrap.sh

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/instance-manager#306]
The bootstrap.sh script has a flag `--aws-api-retry-attempts` that defaults to 3.
If the account is getting throttled heavily, this may cause nodes to fail joining the cluster.
We should set a higher number e.g. 12 to avoid this scenario as much as possible

**Comment by backjo** [comment]
It looks like https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L292 only calls the AWS API if the cluster CA bundle or endpoint is defined.

I wonder if it would make more sense to have the controller inject this information - which should get rid of the throttling issue, as well as decrease startup time since an API call is removed from the critical path.

**Comment by eytan-avisror** [comment]
@backjo great idea - we already have describecluster payload, we can definitely leverage it instead of making those calls
