### ISSUE TITLE
Provision IGs in EKS directly with AWS SDK

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/instance-manager#66]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Currently, the IGs in EKS are provisioned using cloudformation templates (using the `eks-cf` provisioner). While CFN is great, it has a drawback. It prevents any other components/tools from directly modifying the AWS resource or it's dependencies. For e.g. (i) `minion-manager` directly modifies the launchconfig of an ASG to change between spot and on-demand instances or changing the instance type for scaling up/down the instance size would require a change in launch-config. (ii) Adding/removing cloud labels (tags) is required for dynamic changes for cluster-autoscaler and AWS cost analysis tools, etc.

If direct changes are made to the ASG or the launch-config, it creates a drift in the CFN.

**What you expected to happen**:
More of a question: Would it be easier if instance-manager had a new provisioner called `eks-direct` (or something similar) that would directly use the AWS SDK to provision the ASGs? It would solve the above problem of working well with other tools. Another positive side-effect would also be that the ASGs will have deterministic (and prettier) names :-)

Thoughts?

**Comment by eytan-avisror** [comment]
`minion-manager` should support providing recommendation so that it is compatible with `eks-cf` provisioner.

You are talking about making changes to a reconciling object from other components - this will **always** be a problem if you go around the controller.

Even when using SDK to create resources, if a different component changes something under the controller then the next reconcile will try to take it back to whatever the CR is declaring as the desired state.

Regardless of that, we should have an `eks-sdk` provisioner - this however would require significant amount of work and is a matter of prioritizing.

**Comment by shrinandj** [comment]
Agreed that `minion-manager` could implement the events based approach and get the desired result. But what about cases where tags on the ASGs need to be updated at run time (new tags added, old tags removed, etc.). One use-case for that is to enable/disable cluster-autoscaler.

**Comment by eytan-avisror** [comment]
Tags are not overwritten by reconcile, only Cloudformation objects (tags are part of the API call, not the template)

**Comment by eytan-avisror** [comment]
fixed by #83
