### ISSUE TITLE
Rolling upgrade CR not submitted on tag change

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/instance-manager#73]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
An InstanceGroup CR was modified such that new tags were added. This causes the instance-manager controller to reconcile. However, changes to tags does not change the launch-config. As a result instance-manager did not submit any rollingupgrade CRs.

**What you expected to happen**:
Instance-manager should submit CRs in such cases when tags are modified.

**How to reproduce it (as minimally and precisely as possible)**:
- Create and submit an IG CR
- Wait for it to be created
- Update the CR such that the tags are modified
- Notice that:
   - The tags don't get propagated to existing instance
   - There is no rollingupgrade CR submitted

**Comment by eytan-avisror** [comment]
Tags are part of the scaling group (not launch config) hence will never be able to cause a 'drift' that requires a node rotation. 
Forcing the controller to create a new launch config when ASG tags change sounds like incorrect behavior (what if you don't want a rotation due to tags changing?)
But perhaps we should consider a way to force rotation when there are no changes by some mechanism.
Tags are set to propagate to instances by default, however a drift-causing change is required in order to cause the nodes to rotate (for example, adding a node label, changing image or instance type).
I've opened #85 to explore this further
